CREATE TABLE `identi_server`.`dict` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NULL COMMENT '字典项',
  `value` VARCHAR(255) NULL COMMENT '字典值\n',
  `seq` INT NULL COMMENT '排序权重',
  `category` VARCHAR(45) NULL COMMENT '分类',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '字典表';


TRUNCATE TABLE `dict`;

INSERT INTO `dict` (`id`,`name`,`value`,`seq`,`category`)
VALUES 
(uuid(),'黑客','0100',0,'case-type'),
(uuid(),'淫秽色情','0200',0,'case-type'),
(uuid(),'赌博','0300',0,'case-type'),
(uuid(),'网络盗窃','0400',0,'case-type'),
(uuid(),'侵犯知识产权','0500',0,'case-type'),
(uuid(),'诈骗','0600',0,'case-type'),
(uuid(),'传销','0700',0,'case-type'),
(uuid(),'销售禁售物品','0800',0,'case-type'),
(uuid(),'敲诈勒索','0900',0,'case-type'),
(uuid(),'泄密','1000',0,'case-type'),
(uuid(),'危害国家安全','1100',0,'case-type'),
(uuid(),'恐怖','1200',0,'case-type'),
(uuid(),'邪教','1300',0,'case-type'),
(uuid(),'抢劫抢夺','1400',0,'case-type'),
(uuid(),'传统盗窃','1500',0,'case-type'),
(uuid(),'杀人','1600',0,'case-type'),
(uuid(),'制毒贩毒','1700',0,'case-type'),
(uuid(),'侮辱诽谤','1800',0,'case-type'),
(uuid(),'其他','9900',0,'case-type'),
(uuid(),'未知','00',0,'ethnicity'),
(uuid(),'汉族','01',0,'ethnicity'),
(uuid(),'满族','11',0,'ethnicity'),
(uuid(),'回族','03',0,'ethnicity'),
(uuid(),'蒙古族','02',0,'ethnicity'),
(uuid(),'藏族','04',0,'ethnicity'),
(uuid(),'维吾尔族','05',0,'ethnicity'),
(uuid(),'朝鲜族','10',0,'ethnicity'),
(uuid(),'苗族','06',0,'ethnicity'),
(uuid(),'彝族','07',0,'ethnicity'),
(uuid(),'壮族','08',0,'ethnicity'),
(uuid(),'布依族','09',0,'ethnicity'),
(uuid(),'侗族','12',0,'ethnicity'),
(uuid(),'瑶族','13',0,'ethnicity'),
(uuid(),'白族','14',0,'ethnicity'),
(uuid(),'土家族','15',0,'ethnicity'),
(uuid(),'哈尼族','16',0,'ethnicity'),
(uuid(),'哈萨克族','17',0,'ethnicity'),
(uuid(),'傣族','18',0,'ethnicity'),
(uuid(),'黎族','19',0,'ethnicity'),
(uuid(),'傈僳族','20',0,'ethnicity'),
(uuid(),'低族','21',0,'ethnicity'),
(uuid(),'舍族','22',0,'ethnicity'),
(uuid(),'高山族','23',0,'ethnicity'),
(uuid(),'拉枯族','24',0,'ethnicity'),
(uuid(),'水族','25',0,'ethnicity'),
(uuid(),'东乡族','26',0,'ethnicity'),
(uuid(),'纳西族','27',0,'ethnicity'),
(uuid(),'景颇族','28',0,'ethnicity'),
(uuid(),'柯尔克孜族','29',0,'ethnicity'),
(uuid(),'土族','30',0,'ethnicity'),
(uuid(),'达斡尔族','31',0,'ethnicity'),
(uuid(),'松佬族','32',0,'ethnicity'),
(uuid(),'羌族','33',0,'ethnicity'),
(uuid(),'布朗族','34',0,'ethnicity'),
(uuid(),'撤拉族','35',0,'ethnicity'),
(uuid(),'毛南族','36',0,'ethnicity'),
(uuid(),'讫佬族','37',0,'ethnicity'),
(uuid(),'锡伯族','38',0,'ethnicity'),
(uuid(),'阿昌族','39',0,'ethnicity'),
(uuid(),'普米族','40',0,'ethnicity'),
(uuid(),'塔吉克族','41',0,'ethnicity'),
(uuid(),'怒族','42',0,'ethnicity'),
(uuid(),'乌孜别克族','43',0,'ethnicity'),
(uuid(),'俄罗斯族','44',0,'ethnicity'),
(uuid(),'鄂温克族','45',0,'ethnicity'),
(uuid(),'德昂族','46',0,'ethnicity'),
(uuid(),'保安族','47',0,'ethnicity'),
(uuid(),'裕固族','48',0,'ethnicity'),
(uuid(),'京族','49',0,'ethnicity'),
(uuid(),'塔塔尔族','50',0,'ethnicity'),
(uuid(),'独龙族','51',0,'ethnicity'),
(uuid(),'鄂伦春族','52',0,'ethnicity'),
(uuid(),'赫哲族','53',0,'ethnicity'),
(uuid(),'门巴族','54',0,'ethnicity'),
(uuid(),'路巴族','55',0,'ethnicity'),
(uuid(),'基诺族','56',0,'ethnicity'),
(uuid(),'其他','99',0,'ethnicity');
