CREATE TABLE `suspect` (
  `id` varchar(45) NOT NULL,
  `law_case_id` varchar(45) DEFAULT NULL COMMENT '案件id，关联案件表主键',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `case_id` varchar(255) DEFAULT NULL COMMENT '案件编号',
  `case_name` varchar(255) DEFAULT NULL COMMENT '案件名称',
  `case_type_code` varchar(255) DEFAULT NULL COMMENT '案件类型代码',
  `case_type` varchar(255) DEFAULT NULL COMMENT '案件类型',
  `ab` varchar(255) DEFAULT NULL COMMENT '案别代码',
  `ab_name` varchar(255) DEFAULT NULL COMMENT '案别名称',
  `object_id` varchar(255) DEFAULT NULL COMMENT '人员编号',
  `owner_name` varchar(255) DEFAULT NULL COMMENT '姓名（持有人）',
  `bm` varchar(255) DEFAULT NULL COMMENT '别名（曾用名）',
  `identity_id_type_code` varchar(255) DEFAULT NULL COMMENT '证件类型Code',
  `identity_id_type` varchar(255) DEFAULT NULL COMMENT '证件类型名称',
  `identity_id` varchar(255) DEFAULT NULL COMMENT '证件号码',
  `hjdz` varchar(255) DEFAULT NULL COMMENT '户籍地址',
  `dz` varchar(255) DEFAULT NULL COMMENT '现地址',
  `gzdw` varchar(255) DEFAULT NULL COMMENT '工作单位',
  `guojia_code` varchar(255) DEFAULT NULL COMMENT '国家编码',
  `guojia` varchar(255) DEFAULT NULL COMMENT '国家',
  `minzu_code` varchar(255) DEFAULT NULL COMMENT '民族编码',
  `minzu` varchar(255) DEFAULT NULL COMMENT '民族',
  `phone` varchar(255) DEFAULT NULL COMMENT '手机号码',
  `desc` varchar(255) DEFAULT NULL COMMENT '描述',
  `date` varchar(255) DEFAULT NULL COMMENT '采集日期',
  `flag` varchar(255) DEFAULT NULL COMMENT '采集类型',
  `officer_id` varchar(255) DEFAULT NULL COMMENT '采集警员编号',
  `officer_name` varchar(255) DEFAULT NULL COMMENT '采集警员姓名',
  `dept` varchar(255) DEFAULT NULL COMMENT '采集警员单位代码',
  `dept_name` varchar(255) DEFAULT NULL COMMENT '采集警员单位名称',
  `strflag` varchar(255) DEFAULT NULL COMMENT '请求唯一id',
  `str_phone_path` varchar(512) DEFAULT NULL COMMENT '手机绝对路径',
  `strreserved1` varchar(255) DEFAULT NULL COMMENT '保留字段',
  `strreserved2` varchar(255) DEFAULT NULL,
  `errcode` int(11) DEFAULT NULL COMMENT '错误码',
  `errmsg` varchar(255) DEFAULT NULL COMMENT '错误消息',
  `note` varchar(255) DEFAULT NULL COMMENT '备注',
  `col1` varchar(45) DEFAULT NULL,
  `col2` varchar(45) DEFAULT NULL,
  `col3` varchar(45) DEFAULT NULL,
  `col4` varchar(45) DEFAULT NULL,
  `col5` varchar(45) DEFAULT NULL,
  `col6` varchar(45) DEFAULT NULL,
  `col7` varchar(45) DEFAULT NULL,
  `col8` varchar(45) DEFAULT NULL,
  `col9` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='嫌疑人表；部分字段与警综接口保持一致';
